version: '3.9'

services:
  database:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres

  
volumes:
  pgdata:
    driver: local
